---
#---Acesso ao host do Vagrant
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant

# Define o timezone 
time_zone: "America/Sao_Paulo"

common_packages_redhat_like:
  - epel-release
  - vim
  - wget 
  - curl
  - net-tools
  - nano
  - unzip

# url do repositório do zabbix para RHEL
zabbix_rhel_repo: 'http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm'


# IPs 
mysql_ip: "192.168.0.201"
zabbix_srv_ip: "192.168.0.202"
frontend_ip: "192.168.0.203"

# Hostname
mysql_hostname: "mysql-rhel"
zabbix_hostname: "zabbix-rhel"
frontend_hostname: "frontend-rhel"


#---Credencias de acesso ao MYSQL
mysql_root_password: "Senha#Root1!"

zabbix_db_server_user: usr_zbx_srv
zabbix_db_server_pass: "Senha#Zabb1x!"

zabbix_db_front_user: usr_zbx_web
zabbix_db_front_pass: "Senha#Front3nd!"

# DATABASE
zabbix_database: dbzabbix

# Nome que aparece no title do browser ao acessar o zabbix.
zabbix_installation_name: "Zabbix Server via Ansible"
...