---
#---Acesso ao host do Vagrant
ansible_ssh_user: vagrant
ansible_ssh_pass: vagrant

# Define o timezone 
time_zone: "America/Sao_Paulo"

# url do repositório do zabbix para RHEL
zabbix_rhel_repo: 'http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm'

# url do repositório do mysql-server 8
mysql_rhel_repo: 'https://repo.mysql.com/mysql80-community-release-el8-1.noarch.rpm'

# Pacotes bases para ambiente baseado em CentOS
common_packages_redhat_like:
  - epel-release
  - vim
  - wget 
  - curl
  - net-tools
  - nano
  - unzip

# IPs 
BD_SERVER_IP: "192.168.0.201"
ZBX_SERVER_IP: "192.168.0.202"
ZBX_WEB_IP: "192.168.0.203"

# Hostname dos servidores
BD_SERVER_HOSTNAME: "mysql-server"
ZBX_SERVER_HOSTNAME: "zabbix-server"
ZBX_WEB_HOSTNAME: "frontend-web"


#---Credencias de acesso ao MYSQL
MYSQL_ROOT_PASSWORD: "Senha#Root1!"

ZABBIX_DB_SERVER_USER: usr_zbx_srv
ZABBIX_DB_SERVER_PASS: "Senha#Zabb1x!"

ZABBIX_DB_WEB_USER: usr_zbx_web
ZABBIX_DB_WEB_PASS: "Senha#Front3nd!"

# DATABASE
ZABBIX_DB: dbzabbix

# Nome que aparece no title do browser ao acessar o zabbix.
NOME_INSTALACAO_ZABBIX: "Zabbix 5 via Ansible"
...